# Generated by Django 3.2.3 on 2021-05-31 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calorie_app', '0008_food_profilesetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilesetting',
            old_name='Activity',
            new_name='activity',
        ),
    ]
