# Generated by Django 3.2.3 on 2021-06-05 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calorie_app', '0012_alter_profilesetting_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesetting',
            name='profile_pic',
        ),
    ]
