# Generated by Django 3.2.3 on 2021-06-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calorie_app', '0013_remove_profilesetting_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesetting',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to='images/%y'),
        ),
    ]
