# Generated by Django 3.2.3 on 2021-06-05 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calorie_app', '0015_alter_profilesetting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesetting',
            name='profile_pic',
        ),
    ]
