# Generated by Django 3.2.3 on 2021-06-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calorie_app', '0018_alter_food_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesetting',
            name='user',
        ),
    ]
