# Generated by Django 3.2.3 on 2021-06-07 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_calorie_app', '0019_remove_profilesetting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesetting',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProfileSettings', to='my_calorie_app.user'),
            preserve_default=False,
        ),
    ]
