# Generated by Django 3.2.3 on 2021-06-08 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calorie_app', '0022_auto_20210607_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='date',
        ),
        migrations.RemoveField(
            model_name='food',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='food',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
    ]
