# Generated by Django 3.2.3 on 2021-06-08 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_calorie_app', '0024_auto_20210607_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='meal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='my_calorie_app.user'),
        ),
    ]
