# Generated by Django 3.2.3 on 2021-06-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calorie_app', '0026_alter_food_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ManyToManyField(to='my_calorie_app.Food')),
                ('user', models.ManyToManyField(blank=True, to='my_calorie_app.User')),
            ],
        ),
    ]
