# Generated by Django 3.2.3 on 2021-06-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calorie_app', '0027_userfood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='date',
        ),
        migrations.RemoveField(
            model_name='food',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='UserFood',
        ),
    ]
