# Generated by Django 3.2.3 on 2021-06-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_calorie_app', '0028_auto_20210607_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='my_calorie_app.profilesetting'),
        ),
    ]
