# Generated by Django 3.2.3 on 2021-06-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calorie_app', '0029_food_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='profile',
        ),
    ]
