# Generated by Django 3.2.3 on 2021-06-09 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_calorie_app', '0032_remove_food_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesetting',
            name='user',
        ),
        migrations.AddField(
            model_name='food',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='my_calorie_app.user'),
        ),
    ]
