# Generated by Django 3.2.3 on 2021-06-10 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_calorie_app', '0035_remove_food_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('profile_pic', models.FileField(default='/static/css/image/default.png', upload_to='user_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pictures', serialize=False, to='my_calorie_app.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='profilesetting',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='food',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='my_calorie_app.profilesetting'),
        ),
        migrations.AlterField(
            model_name='profilesetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ProfileSettings', to='my_calorie_app.user'),
        ),
    ]
