# Generated by Django 3.2.3 on 2021-06-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calorie_app', '0040_picture_profilesetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='profile_pic',
            new_name='file',
        ),
    ]
